# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestbodyfatfemalevalid():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testbodyfatfemalevalid(self):
    self.driver.get("https://www.calculator.net/body-fat-calculator.html?ctype=metric&csex=f&cage=25&cweightlbs=152&cheightfeet=5&cheightinch=10.5&cneckfeet=1&cneckinch=7.5&cwaistfeet=3&cwaistinch=1.5&chipfeet=2&chipinch=10.5&cweightkgs=70&cheightmeter=178&cneckmeter=50&cwaistmeter=96&chipmeter=92&x=Calculate")
    self.driver.set_window_size(550, 692)
    self.driver.find_element(By.NAME, "cage").click()
    self.driver.find_element(By.NAME, "cage").click()
    element = self.driver.find_element(By.NAME, "cage")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "cage").click()
    self.driver.find_element(By.NAME, "x").click()
    self.driver.find_element(By.CSS_SELECTOR, "font > b").click()
    self.driver.find_element(By.CSS_SELECTOR, "font > b").click()
  
