# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestbodyfatmalenegative():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testbodyfatmalenegative(self):
    self.driver.get("https://www.calculator.net/body-fat-calculator.html")
    self.driver.set_window_size(550, 692)
    self.driver.find_element(By.NAME, "cage").click()
    self.driver.find_element(By.NAME, "cage").click()
    element = self.driver.find_element(By.NAME, "cage")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "cage").click()
    self.driver.find_element(By.NAME, "cage").send_keys("-1")
    self.driver.find_element(By.NAME, "cweightkgs").click()
    self.driver.find_element(By.NAME, "cweightkgs").click()
    element = self.driver.find_element(By.NAME, "cweightkgs")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "cweightkgs").click()
    self.driver.find_element(By.NAME, "cweightkgs").send_keys("-1")
    self.driver.find_element(By.ID, "cheightmeter").click()
    self.driver.find_element(By.ID, "cheightmeter").click()
    element = self.driver.find_element(By.ID, "cheightmeter")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "cheightmeter").send_keys("-1")
    element = self.driver.find_element(By.ID, "cneckmeter")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "cneckmeter")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "cneckmeter")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "metricheightweight").click()
    self.driver.find_element(By.ID, "cneckmeter").click()
    self.driver.find_element(By.ID, "cneckmeter").click()
    element = self.driver.find_element(By.ID, "cneckmeter")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "cneckmeter").send_keys("-1")
    self.driver.find_element(By.ID, "cwaistmeter").click()
    self.driver.find_element(By.ID, "cwaistmeter").click()
    element = self.driver.find_element(By.ID, "cwaistmeter")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "cwaistmeter").send_keys("-1")
    self.driver.find_element(By.NAME, "x").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > font").click()
    self.driver.find_element(By.CSS_SELECTOR, ".rightresult > div").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".rightresult > div")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > font").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > font").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > font")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > font").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > font").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > font")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > font").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > font").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) > font")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > font").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > font").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > font")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > font").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > font").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) > font")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
  
